### ISSUE TITLE
Sophisticated Storage upgrade recipes do not show up in JEI

### ISSUE THREAD

**Issue by EnderMelody** [P3pp3rF1y/SophisticatedStorage#62]
MC: 1.18.2
Forge: 40.1.73
SS: 5.1.107
SC: 5.1.98
recipes to upgrade the chest, barrels and shulker boxes do not show up in JEI, only the dye recipes are shown.

**Comment by P3pp3rF1y** [comment]
Fixed in the latest version on CF

**Comment by Jasman922** [comment]
Still doesnt work for me
![image](https://github.com/user-attachments/assets/9bd4e1db-79ca-4eaa-8983-8530861ae257)
Those are the versions of the mods I have, and newest JEI on 1.19.2

**Comment by Jasman922** [comment]
Also, with the crafting upgrade in a backpack, trying to fill in a recipe with the JEI +, it will crash
